- README.md
> Fix fusion-react path

- docs/guides/getting-started.md
> Fix font loading documentation

- package.json
- src/__tests__/__browser__/sanitization.js
- src/sanitization.js
> Expose browser unescape

- src/plugin/__tests__/plugin.js
- src/plugin/plugin/plugin-server.js
> Pass null for ctx rather than an empty object

- README.md
- docs/guides/configuring-plugins.md
- docs/guides/creating-a-plugin.md
- docs/guides/creating-endpoints.md
- docs/guides/creating-providers.md
- docs/guides/dependencies.md
- docs/guides/getting-started.md
- docs/guides/modifying-html-template.md
> Add more plugin architecture documentation

- .buildkite/browserTests
- .buildkite/nodeTests
- .codecov.yml
- docker-compose.yml
- package.json
- src/virtual/index.js
- yarn.lock
Fixes https://github.com/fusionjs/fusion-core/issues/23
> Add coverage to buildkite

- .buildkite/browserTests
- .buildkite/nodeTests
- docker-compose.yml
- package.json
- yarn.lock
Fixes https://github.com/fusionjs/fusion-core/issues/28
> Switch to codecov bash uploader and expose env vars

- docs/guides/getting-started.md
A few things I noticed as I was going through the getting started steps.
> Update getting started docs

- package.json
- src/__tests__/__browser__/index.js
- src/__tests__/__node__/index.js
- src/__tests__/simulate.js
- src/client.js
> Update client side rendering logic to mimick servers with regards to ctx.rendered

- src/__tests__/simulate.js
- src/client.js
> Return promise from client renderer middleware

- src/__tests__/__browser__/index.js
- src/__tests__/simulate.js
- src/client.js
- src/plugin/compose.js
- src/server.js
> Fix double render bug

- README.md
- docs/guides/creating-a-plugin.md
- docs/guides/creating-endpoints.md
- docs/guides/creating-providers.md
- docs/guides/dependencies.md
- docs/guides/getting-started.md
- docs/guides/what-is-fusion.md
- docs/guides/working-with-secrets.md
Created with fusion-orchestrate.
> Use absolute link urls in docs

- docs/migrations/00043.md
- src/__tests__/__node__/index.js
- src/__tests__/simulate.js
- src/__tests__/virtual.js
- src/client.js
- src/server.js
> Remove the simulate API in favor of using fusion-test-utils

- src/__tests__/__node__/app.js
- src/server.js
> Fix issue with webpack_public_path and cdns

- src/__tests__/__node__/app.js
- src/server.js
> Add support for crossorigin scripts

- package.json
- src/__tests__/app.node.js
- src/__tests__/index.browser.js
- src/__tests__/index.node.js
- src/__tests__/sanitization.browser.js
- src/__tests__/sanitization.node.js
- src/__tests__/timing.node.js
- yarn.lock
Created with fusion-orchestrate.
> Upgrade create-universal-package@^3.2.x

- src/__tests__/dependency-resolution.js
- src/base-app.js
Fixes #81, summarized below:
Includes:
* Additional check against malformed input for plugins in `base-app.js`
* Additional unit tests to ensure no regression in the future
> Added a check against malformed plugin values

- src/__tests__/timing.node.js
> Add additional debug information to intermittently failing unit test

- src/__tests__/app.node.js
- src/__tests__/index.browser.js
- src/__tests__/index.node.js
- src/__tests__/sanitization.browser.js
- src/__tests__/sanitization.node.js
- src/__tests__/simulate.js
- src/__tests__/timing.node.js
- src/__tests__/virtual.js
- src/client.js
- src/index.js
- src/plugin/__tests__/compose.js
- src/plugin/__tests__/plugin.js
- src/plugin/__tests__/singleton-plugin.js
- src/plugin/__tests__/test.js
- src/plugin/compose.js
- src/plugin/index.js
- src/plugin/plugin/plugin-client.js
- src/plugin/plugin/plugin-server.js
- src/plugin/plugin/plugin.js
- src/plugin/singleton-plugin/singleton-plugin.js
- src/sanitization.js
- src/server.js
- src/timing.js
- src/virtual/index.js
Created with fusion-orchestrate.
> Add short MIT license header to all source files

- README.md
- flow-typed/fusion-core.js
- flow.js
- package.json
- src/__tests__/dependency-resolution.js
- src/__tests__/enhance.js
- src/base-app.js
- yarn.lock
> Add support for app.enhance

- src/__tests__/dependency-resolution.js
- src/base-app.js
> Update resolution to throw if extraneous configuration is registered

- package.json
- src/server.js
- yarn.lock
> Upgrade prettier version and re-lint

- flow-typed/fusion-core.js
- flow.js
- src/__tests__/dependency-resolution.js
- src/__tests__/enhance.js
- src/__tests__/render.js
- src/__tests__/timing.js
- src/base-app.js
- src/create-token.js
- src/index.js
- src/plugins/timing.js
- src/tokens.js
See [PR#124](https://github.com/fusionjs/fusion-core/pull/124/commits/235f8c7b338ebf580929c1d8b4d6e3eb44132492)
> Merge 'Support optional dependencies #124' to master

- src/create-token.js
Fixes [this PR comment](https://github.com/fusionjs/fusion-tokens/pull/35#discussion_r165252181).
> (Minor) Fix Flow typing for `TokenImpl`

- flow-typed/fusion-core.js
- flow.js
- src/__tests__/dependency-resolution.js
- src/__tests__/enhance.js
- src/__tests__/render.js
- src/create-token.js
- src/plugins/timing.js
> Add export of Token and FusionPlugin types

- docs/guides/dependencies.md
- docs/guides/working-with-secrets.md
Fixes [#142](https://app.zenhub.com/workspace/o/uber-web/web-platform-tasks/issues/421)
* docs/guides/dependencies.md | [rendered](https://github.com/AlexMSmithCA/fusion-core/blob/b0222d03f60474bc0e3d74b3844db04eb19b1b1a/docs/guides/dependencies.md)
* docs/guides/working-with-secrets.md | [rendered](https://github.com/AlexMSmithCA/fusion-core/blob/b0222d03f60474bc0e3d74b3844db04eb19b1b1a/docs/guides/working-with-secrets.md)
> More guides docs changes to use Dependency Injection & `createPlugin` API

- src/__tests__/render.js
- src/base-app.js
- src/client-app.js
- src/server-app.js
> Fix issue with render plugin order

- README.md
- flow-typed/fusion-core.js
- flow.js
- src/__tests__/cleanup.js
- src/base-app.js
> Add support for async plugin cleanup function

- src/plugins/server-renderer.js
- src/plugins/timing.js
> Fix render and upstream timing

- README.md
- docs/guides/creating-a-plugin.md
- docs/guides/creating-endpoints.md
- docs/guides/creating-providers.md
- docs/guides/dependencies.md
- docs/guides/framework-comparison.md
- docs/guides/getting-started.md
- docs/guides/modifying-html-template.md
- docs/guides/universal-code.md
- docs/guides/what-is-fusion.md
Created with fusion-orchestrate.
> Replace FusionJS with Fusion.js

- package.json
- src/get-env.js
- src/index.js
- src/plugins/server-context.js
- src/plugins/ssr.js
- src/server-app.js
- yarn.lock
> Move environment variable loading into fusion-core

- README.md
- src/__tests__/index.node.js
- src/plugins/ssr.js
> Add support for ctx.template.bodyAttrs

- src/__tests__/index.node.js
- src/plugins/server-renderer.js
- src/plugins/ssr.js
> Support redirects from ssr routes

- flow-typed/fusion-core.js
- flow.js
- package.json
- src/create-token.js
- src/flow/flow-fixtures.js
Fixes [#681](https://app.zenhub.com/workspace/o/uber-web/web-platform-tasks/issues/681).
> Update types for FusionPlugin and add some sanity tests

- package.json
- src/create-plugin.js
- src/flow/flow-fixtures.js
Fixes [#681](https://app.zenhub.com/workspace/o/uber-web/web-platform-tasks/issues/681).
> More flow sanity checks

- flow-typed/fusion-core.js
> Restore typing for app.register

- README.md
add and update manual document for Context API based on Koa Context
> Create Documented Context API properties

- README.md
Updates readme with a short blurb about the HttpServerToken
> Add HttpServerToken to readme

- src/__tests__/cleanup.js
- src/__tests__/index.node.js
- src/base-app.js
- src/base-app.js.flow
- src/plugins/ssr.js
- src/server-app.js
- src/types.js
Tackled a few `// $FlowFixMe` comments that were not too controversial (hopefully). Mainly dealt with type refinements and declaring types that were not present.
> Remove a few // FlowFixMe's

- package.json
- src/plugins/ssr.js
Newer fusion-cli versions don't need this custom code anymore. See https://github.com/fusionjs/fusion-cli/pull/451 for more context.
> Delete vestigial chunk preloading code

- src/__tests__/app-interface.js
- src/__tests__/dependency-resolution.js
- src/base-app.js
- src/base-app.js.flow
RFC: https://github.com/fusionjs/rfcs/pull/11
Depended on by: https://github.com/fusionjs/fusion-react/pull/163
> Expose resolved services as a private API

- src/__tests__/index.node.js
- src/plugins/ssr.js
This updates the default logic for deciding on server side render to
handle a whitelist of bots. Eventually we may want a more robust solution 
to this problem, but the whitelist should suffice for a temporary fix.
> Add bot whitelist

- src/__tests__/index.node.js
- src/server-app.js
Bridging and making proxy: true uniform across dev and production.
> Enable proxy by default

- package.json
- Resolve timing.end on errored requests ([#333](https://github.com/fusionjs/fusion-core/pull/333))
- Allow orphan plugins when registered with a plugin enhancer ([#331](https://github.com/fusionjs/fusion-core/pull/331))
- Implement CI for multiple node versions ([#328](https://github.com/fusionjs/fusion-core/pull/328))
- Enable proxy by default ([#327](https://github.com/fusionjs/fusion-core/pull/327))
- Set koa proxy flag to true in production env ([#326](https://github.com/fusionjs/fusion-core/pull/326))
- Freeze TokenType enum map for Flow ([#325](https://github.com/fusionjs/fusion-core/pull/325))
> Release v1.9.0

- package.json
- Improve token tracking ([#340](https://github.com/fusionjs/fusion-core/pull/340))
- Disable flow temporarily for failing 0.85 upgrade ([#337](https://github.com/fusionjs/fusion-core/pull/337))
- Fix aliasing with optional tokens ([#335](https://github.com/fusionjs/fusion-core/pull/335))
> Release v1.10.0

- package.json
- Upgrade flow-bin to latest and fixes ([#356](https://github.com/fusionjs/fusion-core/pull/356))
> Release v1.10.3

- src/__tests__/exports.js
- src/__tests__/virtual.js
- src/index.js
- src/virtual/index.js
For: https://github.com/fusionjs/fusion-cli/pull/720
> Export workerUrl virtual method

- package.json
- Export workerUrl virtual method ([#360](https://github.com/fusionjs/fusion-core/pull/360))
> Release v1.10.4-1

- package.json
- Export workerUrl virtual method ([#360](https://github.com/fusionjs/fusion-core/pull/360))
> Release v1.10.4-2

- package.json
- Export workerUrl virtual method ([#360](https://github.com/fusionjs/fusion-core/pull/360))
> Release v1.10.4

- src/__tests__/index.node.js
- src/__tests__/sanitization.node.js
- src/sanitization.js
Escaping / is unnecessary and causes issues when escaping html that includes urls.
> Update html escape logic to ignore /
