.flowconfig, flow-typed/npm/koa_v2.x.x.js, lib/index.js.flow, src/client.js, src/context.js, src/index.js, src/plugin/index.js, src/plugin/plugin/plugin-client.js, src/plugin/plugin/plugin-server.js, src/plugin/plugin/plugin.js
Proof of Concept for adding Flow support to _fusion-core_:
- Added sample types to the `Plugin` classes
- Leverage `flow gen-flow-files` to generate type declarations for exports
-- I don't think this has officially released yet (i.e. is experimental) so there are still some quirks
Based upon upcoming H1 priorities, it isn't clear when we'll make a larger push to Flow-ify all of our plugins.  I suspect we'll want to support types for our consumer-exposed exports first (e.g. Plugins, Context, Utility functions, ...) and follow up with improving flow coverage within our packages afterwards.
*PR will not be merged.  Used to reference in the future and show off the PoC*
=> PoC (#253) Added example types for Plugin classes

src/__tests__/__browser__/index.js, src/__tests__/__node__/index.js, src/client.js
Currently the render can fail silently, leaving us in the dark. This bubbles errors up instead of swallowing them.
Fixes #50
=> Do not swallow rendering errors

src/__tests__/timing.node.js
There is no minimum guaranteed time that microtasks take, so this often executes faster than 10ms in CI. We should probably just remove assertions against real time regardless in this test file, but just going to update it to be a value we should be able to consider safe.
Fixes #94
=> Fix intermittent timing test

src/base-app.js
Tokens are functions and we get an unhelpful function when trying to show the user an error message. Executing the function will show the user which token actually has the issue.
Fixes #112
=> Execute token function on error

flow-typed/fusion-core.js, flow.js, src/__tests__/dependency-resolution.js, src/__tests__/enhance.js, src/__tests__/render.js, src/__tests__/timing.js, src/base-app.js, src/create-token.js, src/index.js, src/plugins/timing.js, src/tokens.js
Fixes #95.  Implements proposed **Option 1**:
```js
// Defining the token
import {createToken} from 'fusion-tokens';
import type {Token} from 'fusion-tokens';
type Fetch = (input: string | Request, init?: RequestOptions) => Promise<Response>;
export const FetchToken: Token<Fetch> = createTaoken('FetchToken');
// Using the token
import {createPlugin} from 'fusion-core';
export default createPlugin({
deps: {
fetch: FetchToken, // required token example
logger: LoggerToken.optional, // optional token example
},
});
```
=> Support optional dependencies

src/__tests__/dependency-resolution.js, src/create-token.js
Fixes #129:
> #### Problem/Rationale
> 
> Optional Tokens are not as explicit as they should be, and should allow for only:
> * `undefined` - no value registered
> * `T` - value that was registered
> 
> Today, they are [maybe](https://flow.org/en/docs/types/maybe/) values (which allows `nulls`).
> 
> #### Solution/Change/Deliverable
> 
> Change type signature of `Token<T>` to:
> 
> ```js
> type Token<T> = {
>   (): T,
>   optional: () => void | T,
> };
> ```
>
=> Scope optional Tokens to `undefined` or provided value

.npmignore, package.json
Due to the create-universal-package upgrade this package now exports an index.js.flow which flow will attempt to use for flowtyping. This file currently does not export any of the types within flow.js, or flow-typed/fusion-core.js, so this causes flow to fail. Not generating this file should allow us to have flow passing as before.
I'm not sure if this gets us anything for type safety when importing fusion-core, but it does not cause flow to fail for other plugins. Ideally we move flowtypes into JS files for this package.
=> Skip fusion-core flow file generation

flow-typed/fusion-core.js
The argument can be a plugin or a function. Infer it to avoid messy parameterization
=> Fix type of `render` arg

flow-typed/fusion-core.js
Existing type definitions are ambiguous and cause errors. This replaces them with a looser type
=> Disambiguate enhance type

README.md
The docs repo (fusionjs.github.io) is now the primary source of truth for docs and we should integrate the table of contents within that repository instead. I will open up a PR there to add a navigation with these links.
Rendered:
=> Remove guide links

README.md, flow-typed/fusion-core.js, src/__tests__/exports.js, src/__tests__/index.node.js, src/base-app.js, src/index.js, src/plugins/ssr.js, src/server-app.js, src/tokens.js
This implements two SSR detection features.
* **Additional non-SSR whitelisted extensions**
Adds the following extensions: (js|gif|jpg|png|pdf|json)
* **SSRDeciderToken for enhancing SSR logic**
Exports our current SSR logic as a new token, SSRDeciderToken, which can be enhanced through the DI system. This is a change which keeps our API surface fairly small, isn't difficult to support, and allows folks to control server rendering while we iterate on a future solution.
For more discussion and a breakdown of supported URIs see: https://github.com/fusionjs/fusion-core/issues/116#issuecomment-369430656
Fixes #45 
Fixes #116
=> Proposal: Implement additional SSR detection and control

flow-typed/fusion-core.js
Fixes the issue where Koa type definitions were not visible to consumers of `fusion-core` type definitions:
=> Encapsulate all types and imports in the 'fusion-core' module

flow-typed/fusion-core.js
Fixes [#678](https://app.zenhub.com/workspace/o/uber-web/web-platform-tasks/issues/678)
> #### Problem/Rationale
> 
> Type definition for `FusionPlugin<Deps, Service>` breaks on `$ObjMap` call if `Deps` resolves to `undefined` (or non-object).
> 
> #### Solution/Change/Deliverable
> 
> Ensure that the `$ObjMap` call is invoked on type `Object`.
See a live example of the error: [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCiAHugE4CGAxugEq7oCupAdgCo74C8YAPAGoA+ABRCAlGE4CwfcZOkBuDBzAAxBgGcAlnGYAFGAwDmm5jwAiubOoA0YAMq5SAN02VcU7gG9UYMABNLdQB+AC4wCytrHzBsUjgXAOCwoQj1MIASAHkAIwArAFlybHNA22IyKlp6JjYOAVkpB2dXXCiAX0VfLrBUShhydXVVDW1mAEFsbDBvX1JcY3V0RxLI+0cXN2F9IxMwtS0dbeNTVNsmjfdRMMXSE0Np6NnqljAAIgALXBh4V86wNtQHVQqCgDGY1FGYDg2HQo3I30wdAWS1I6jGRxMQmiRWwexGOgm2CivnUcAAtrgMcxQsMDnoDMceCB …
=> Fix fusion-core libdef type definitions file

src/__tests__/dependency-resolution.js, src/__tests__/enhance.js, src/base-app.js
This updates error messages to provide more context around which Plugin was attempting to require a missing dependency.
For a normal missing dependency:
> Could not resolve token: "DepA", which is required by plugins registered with tokens: "MyParentToken". Did you forget to register a value for "DepA"?
For a missing dependency used by an enhancer plugin:
> Could not resolve token: "DepA", which is required by plugins registered with tokens: "EnhancerOf\<MyEnhancedToken>". Did you forget to register a value for "DepA"?
=> Display more context when missing dependencies

src/base-app.js.flow, src/flow/flow-fixtures.js, src/types.js
Right now any call to app.cleanup results in uncovered code due to the any. Instead prefer coverage over flexibiltiy, and force apps to manually cast if needed. In the future we can open this up more if apps start using this for other things.
=> Lock down cleanup return type

src/flow/flow-fixtures.js, src/get-env.js
This was broken when we started doing inline typing. Declare the default export to fix existing flow usage.
=> Fix flow typing for getEnv

src/index.js, src/tokens.js
Adds a token that represents the node HTTP server instance, used for DI for Websocket support.
I'm not 100% sure if this is the right place to put this token. `fusion-cli` didn't seem like the right place either and it's either here or a plugin that does nothing but expose this token.
I think in the future if we were to build a plugin that encapsulates Websocket logic the token could be moved there.
=> Add HttpServerToken token

src/flow/flow-fixtures.js, src/sanitization.js
It seems that this has just been wrong for a long time. Recent fusion-release-verification jobs have been failing with:
=> Fix sanitization types

package.json, src/plugins/ssr.js
- Moves execution of critical (preloaded) async chunks before "sync" chunks
- Enforces usage of fusion-cli version 1.2.2 or newer (i.e. versions of  fusion-cli using webpack 4)
This will eventually allow for the removal of our custom chunk preloading code (needed in webpack 3 and older)
=> Change script order, add fusion-cli peer dependency

src/plugins/ssr.js
CSP nonces were missing for initial chunk script tags, this violates CSP in strict-dynamic mode.
=> Add CSP nonces to chuck script tags

src/plugins/client-renderer.js, src/plugins/server-renderer.js
We should provide additional `ctx` for the custom renderer could have additional control logic.
=> Provide additional ctx for RenderToken

src/create-token.js
Minor Flow fix to avoid `$FlowFixMe`, given we know the return type for `createToken`.
=> Apply type casting in createToken to avoid $FlowFixMe

src/base-app.js, src/plugins/ssr.js, src/server-app.js, src/tokens.js, src/types.js
The SSR body template is tightly coupled with the build system (fusion-cli) but this code lives in fusion-core. Moving the SSR body template into the DI system will allow fusion-cli to register its own SSR body template (ensuring it is always the correct code). This change also makes fusion-core and fusion-cli properly decoupled as presumably an alternative build system could register its own template as well.
=> Move SSR body template into DI system

src/__tests__/dependency-resolution.js, src/__tests__/enhance.js, src/base-app.js
This PR makes a change to allow extraneous values to be registered in the case where they were depended on at some point during the application setup process. This is common during testing when you might register a mock that doesn't share all the same dependencies as the real implementation. This also could be useful when sharing code.
=> Refactor extraneous registration logic to support plugins that are re-registered

src/base-app.js, src/index.js, src/plugins/ssr.js, src/server-app.js, src/tokens.js
- Make `SSRBodyTemplate` optional by using old built-in template if not registered.
- Export two new tokens:
-  `CriticalChunkIdsToken` (for use in future versions of fusion-cli, fusion-react, fusion-plugin-i18n, etc.)
-  `RoutePrefixToken` (for use in future versions of fusion-cli, fusion-plugin-react-router, etc.)
- These tokens will eventually be used instead of the corresponding context properties, which will be deprecated in a future version of fusion-core.
=> Make SSRBodyTemplate optional, export RoutePrefixToken and CriticalChunkIdsToken

src/plugins/ssr.js
This fix is needed for preload tags to work when using a Strict CSP policy.
=> Add CSP nonce to preload link tags

src/plugins/ssr.js
Per https://developers.google.com/web/updates/2017/12/modulepreload preload hints must be using the same credentials mode as the script tags for there to be a cache hit.
This PR ensures that preload hints have the same crossorigin attribute as the script tags to prevent double fetching.
=> Fix double fetching resulting from preload hint cache miss if using CDN

src/__tests__/enhance.js, src/base-app.js, src/create-token.js, src/types.js
TL;DR: People have been running into an issue where having multiple versions of a same plugin would cause the DI system to throw errors about missing dependencies. The error was cryptic and difficult to troubleshoot.
This PR  exposes stack information about the missing token as well as potential problematic duplicated tokens, and it offers actionable suggestions to fix the issue.
I labeled this PR w/ the feature flag because this diff adds a `stack` field to `Token`
```
// Before
Error: Could not resolve token: "A", which is required by plugins registered with tokens: "UnnamedPlugin". Did you forget to register a value for "A"?
at resolveToken (/Users/lhorie/Documents/aaa/node_modules/fusion-core/src/base-app.js:202:15)
at resolvePlugin …
```
=> Make missing token error more actionable

src/create-token.js
`$Values<>` only works like an enum type when the object is frozen.
https://flow.org/try/#0MYewdgzgLgBAcgeQCoH0CicCqBZGBeGAbwCgYYBBALhgHIBDGgGlJgCFqaAjJ4gXwG5iUAJ4AHAKbwQUNGACuAW3wwAJADU6AGzniIAHhESQAM3jJ0WbAD5BxUJFgYcyhJwBW44FAB0xgE7i4gBe4gAUJGRUtAzMZOy03My8AJSChpKyisrqWjr66SYwTta29tAwYNKZCtRwVfJKBDTANIJlsP4gIWDV1NXKza3EQA
=> Freeze TokenType enum map for Flow

src/__tests__/enhance.js, src/base-app.js
This is useful in situations where the default value on a token
does not provide plugin functionality (ex: middleware) but an
enhancer wishes to add this functionality.
=> Allow orphan plugins when registered with a plugin enhancer

src/__tests__/timing.js, src/plugins/timing.js
We should always resolve timing.end, even if the request
errors (via ctx.throw for example).
=> Resolve timing.end on errored requests

src/__tests__/dependency-resolution.js, src/base-app.js
Previously to alias an optional dependency of a plugin, one would have to alias the "optional type token" given the alias map key was `TokenImpl` instead of `Ref()`.
```js
app
.register(PluginWithOptionalDep)
.alias(OptionalDep.optional, AlternativeDep);
app.register(AlternativeDep, AlternativePlugin);
```
->
```js
app
.register(PluginWithOptionalDep)
.alias(OptionalDep, AlternativeDep);
app.register(AlternativeDep, AlternativePlugin);
```
=> Fix aliasing with optional tokens

package.json
`fusion-cli` doesn't appear to be actually used anywhere in `fusion-core`
This PR removes it from package.json.
Rationale: fusion-cli depends on fusion-core, so we want to avoid having fusion-core cyclically depend on fusion-cli in order to allow the two to co-exist in a monorepo where fusion co-dependencies are linked together via symlinks or similar mechanisms. Cyclical dependencies cause problems for tooling that relies on file system traversal, and need to be avoided.
=> Remove fusion-cli peer dep

package.json, src/__tests__/sanitization.node.js, yarn.lock
Upgrades `flow-bin` to `v0.92.0` and resolves the following complaint:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/__tests__/sanitization.node.js:36:12
Cannot call null.toString because property toString is missing in null [1].
33│   const userData = '<malicious data="" />';
34│   const value = html`
35│     <div>${userData}</div>
[1] 36│     ${null.toString()}
37│   `;
38│   t.equals(typeof value, 'object');
39│   t.equals(
Found 1 error
```
=> Upgrade flow-bin to latest and fixes

.eslintignore, flow-typed/npm/koa_v2.x.x.js, package.json, yarn.lock
Fixes a koa flow-typed def regression
=> Upgrade flow to 0.93.0

src/__tests__/app.node.js, src/__tests__/index.node.js, src/__tests__/test-helper.js, src/plugins/ssr.js
Previously we were returning true from the SSRDecider for all requests with a
user agent matching a bot. This caused issues when handling non GET routes.
This updates the logic to also check for the request method === GET.
=> Fix SSR Decider for Bots

src/__tests__/index.node.js, src/plugins/ssr.js
This will ensure svg and sourcemap asset requests will not result in an SSR being triggered
=> Include svg and js.map in the extension list determining SSR
